### ISSUE TITLE
Naming convensions for Scribble Protocols

### ISSUE THREAD

**Issue by thefangbear** [scribble/scribble-java#145]
I noticed that scribblec generates package paths with capitalized name if I use capitalized protocol names, i.e. if I name my global protocol "Sample" under module `org.example` with file name `scribble`, the Java package path will be inconsistent with Java naming convensions: `org.example.scribble.Sample` is the package name. But it seems like in Scribble doc, capitalized names are preferred as they are also used as part of class name, and the naming convention for Java classname is indeed Capitalized. Is there a way to generate API packages that are both compliant with Scribble and with Java conventions?

**Comment by rhu1** [comment]
Closing due to age -- apologies this was not replied to at the time.
As you said, some names in the source protocol are directly used as both package and class names in the generated API -- this means Java naming conventions will necessarily be violated because, either a package will be capitalised or a class will not.
We're not planning to address this at this moment but we'll keep this issue in mind. 
Of course, the codegen can be hacked to work around this in various ways.  Cf. the simplisitic naming methods [**here**](https://github.com/scribble/scribble-java/blob/53e520a8cd916bfadd20db947568f676210d350c/scribble-codegen/src/main/java/org/scribble/codegen/java/statechanapi/ScribSockGen.java#L216).
E.g., the package names could be formatted to all lowercase.
