### ISSUE TITLE
Running Adder Demo

### ISSUE THREAD

**Issue by lrjm** [scribble/scribble-java#147]
I am an undergraduate CS student,  as part of my honours thesis I have been studying MPST and trying to find use cases for Scribble. I've been trying to follow the tutorial at http://www.scribble.org/docs/scribble-java.html, and have been trying to execute the Adder implementations provided. 

I apologize that I am still new to Java and maven so I'm probably just not doing something very simple. If anyone can help it would be appreciated.

When I try to compile, for instance, AdderS.java, I get the following error:
```
scribble-java-master\scribble-demos\scrib\tutorial\src\tutorial\adder\AdderS.java:16: error: package tutorial.adder.Adder.Adder does not exist
import static tutorial.adder.Adder.Adder.Adder.Add;
                                        ^
```

Which makes me think that I need to compile the file tutorial/adder/Adder/Adder/Adder.java

Attempting this gives the error

```
scribble-java-master\scribble-demos\scrib\tutorial\src\tutorial\adder\Adder\Adder\Adder.java:7: error: package org.scribble.core.type.name does not exist
import org.scribble.core.type.name.Role;
                                  ^
```
Am I going about this the wrong way? Have I missed some part of setting up the software? Or am I not supposed to try to compile these files this way? I am using Windows 10 and trying to run the software on the command line. I apologize again for my inexperience.

**Comment by lrjm** [comment]
I've also built the project in Eclipse, but can't seem to run AdderS/AdderC. Any tips?

**Comment by rhu1** [comment]
Closing due to age -- apologies this was not replied to at the time.
If you've successfully generated the API(s), then compiling/running the AdderS/AdderC programs should be the same as for any Java program -- check you have the all the necessary packages in your runtime classpath.  If you're missing any, the run-time error messages should give some hints as to which.
Feel free to reopen if this is still an issue.
